#!/usr/bin/env bash
# Transfers a file from a client to a server

if [[ $# -lt 3 ]]; then
	echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY';
	exit 1;
fi

file_path=$1;
remote_ip=$2;
username=$3;
key_file=$4;

scp -o "StrictHostKeyChecking=no" \
	-i "$key_file" \
	"$file_path" \
	"$username"@"$remote_ip":~;

