#!/usr/bin/env bash
# Installs nginx and serves a custom-page in the server

custom_html_file='custom-hello.html'
default_html_file='index.nginx-debian.html'
html_path='/var/www/html'
sites_enabled_path='/etc/nginx/sites-enabled'
sites_available_path='/etc/nginx/sites-available'

apt install -y nginx;
touch "$html_path/$custom_html_file"

html_content="<!DOCTYPE html>
<html>
	<head></head>
	<body>
		<h1>Hello World!</h1>
	</body>
</html>"

echo "$html_content" > "$html_path/$custom_html_file"

# keep original nginx html file as backup
if [[ -f "$html_path/$default_html_file" ]]; then
	mv "$html_path/$default_html_file" "$html_path/$default_html_file".bak
fi

# add custom file to nginx configuration file
sed -i "s/$default_html_file/$default_html_file $custom_html_file/" "$sites_available_path"/default

# delete existing `default` link, and re-construct it
rm "$sites_enabled_path"/default
ln -s "$sites_available_path"/default "$sites_enabled_path"/

nginx -s reload;

