#!/usr/bin/env bash
# Installs nginx and serves a page in the server

custom_html_file='custom-hello.html'
default_html_file='index.nginx-debian.html'
html_path='/var/www/html'
sites_enabled_path='/etc/nginx/sites-enabled'

apt install -y nginx;
touch "$html_path/$custom_html_file"

custom_config="server {
	listen 80 default_server;
	server_name _;

	location / {
		default_type text/plain;
		return 200 \"Hello World!\";
	}
}"

html_content="<!DOCTYPE html>
<html>
	<head></head>
	<body>
		<h1>Hello World!</h1>
	</body>
</html>"

echo "$html_content" > "$html_path/$custom_html_file"

# keep original nginx html file as backup
if [[ -f "$html_path/$default_html_file" ]]; then
	mv "$html_path/$default_html_file" "$html_path/$default_html_file".bk
fi

# add custom file to nginx configuration file
sed -i "s/$default_html_file/$default_html_file $custom_html_file/" /etc/nginx/sites-available/default

# keep original config, and regenerate new config with custom instructions
mv "$sites_enabled_path/default" "$sites_enabled_path/default.bk"
touch "$sites_enabled_path/default"
echo "$custom_config" > "$sites_enabled_path/default"

# soft link 
nginx -s reload;

