#!/usr/bin/env bash
# Bash script that:
# - pings an IP address passed as an argument.
# - Accepts a string as an argument
# - Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if
# no argument passed
# - Pings the IP 5 times

MAX_PINGS=5

if [ $# == 0 ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c $MAX_PINGS "$1"
fi
