#!/usr/bin/env bash
# displays numbers from 1 to 100
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number
# In a list format

START_NUM=1
STOP_NUM=100

for (( i=START_NUM; i<=STOP_NUM; i++ )); do
	if (( $i%15==0 )); then
		echo "FizzBuzz"
	elif (( $i%3==0 )); then
		echo "Fizz"
	elif (( $i%5==0 )); then
		echo "Buzz"
	else
		echo "$i"
	fi
done
