#!/usr/bin/env bash
# Prints "Best School" 10 times, with a "Hi" at iteration 9
printCount=0
maxPrints=10

while [ $printCount -lt $maxPrints ]
do
	if [ $printCount == 8 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((printCount++))
done

